change documentation for the case of openvpn

diff --git a/scripts/run-client b/scripts/run-client
--- a/scripts/run-client
+++ b/scripts/run-client
@@ -1,13 +1,15 @@
 #!/usr/bin/env bash
-set -ex
+set -e
+
+PATH=$PATH:/usr/local/sbin/
 
 NS=`cat lib/config.ml | grep external_ip | awk '{print $4}' | sed 's/"//g'`
 IODINE_DOMAIN="i.d1.signpo.st"
 NODE_NAME=eeepc
 
 PASS=`cat scripts/PASSWD`
-if [ "`ps -e | grep iodine | wc -l `" -lt 1 ]; then
-  if [ $NS -eq "" ]; then
+if [ "`ps -e | grep iodine | wc -l `" -lt 2 ]; then
+  if [ "$NS" -eq "" ]; then
     iodine -P ${PASS} "$IODINE_DOMAIN";
   else
     iodine -P ${PASS} $NS "$IODINE_DOMAIN"
@@ -29,30 +31,30 @@ SIG_PORT=42425
 # delete all arp entries, so that we will discover them using openflow
 # arp -n | awk '/(^[0-9]+\.?)+/ {print $1;}' | xargs -I '{}' arp -d '{}'
 
-# clean up ports from openvswitch switch
-ovs-vsctl show | grep Interface | grep tap | awk '{print $2;}' \
-    | xargs -I '{}' ovs-vsctl del-port br0  '{}'
-ovs-dpctl show br0 | grep tap | awk '{print $3}' \
-  | xargs -I '{}' ovs-vsctl del-port br0  '{}'
-
-# clean up ip addresses from bridge interface
-ip addr show  dev br0 | grep 10\\.\[23\]\\. | awk '{print $2;}' \
-  |  xargs -I '{}'  ip addr del  '{}' dev br0
-# clean up ip addresses from bridge interface
-ip addr show  dev br0 | grep 172\\.31\\. | awk '{print $2;}' \
-  |  xargs -I '{}'  ip addr del  '{}' dev br0
-
-# cleaning default links for sp addresses
-route -n | grep 172\\.31\\.  | awk '{print $1" netmask "$3" gw "$2;}' \
-    | xargs -I '{}' echo route del -net '{}' > /tmp/sp_route_cleanup.sh
-
-# cleanning up ssh routes
-route -n | grep 10\\.\[23\]\\. | awk '{print $1" netmask "$3" gw "$2;}' \
-    | xargs -I '{}' echo route del -net '{}' >> /tmp/sp_route_cleanup.sh
-
-sudo sh /tmp/sp_route_cleanup.sh   
-
-ovs-ofctl del-flows br0
-ovs-ofctl add-flow br0 hard_timeout=0,idle_timeout=0,priority=1,in_port=1,action=LOCAL
-ovs-ofctl add-flow br0 hard_timeout=0,idle_timeout=0,priority=1,in_port=LOCAL,action=output:1
+# # clean up ports from openvswitch switch
+# ovs-vsctl show | grep Interface | grep tap | awk '{print $2;}' \
+#     | xargs -I '{}' ovs-vsctl del-port br0  '{}'
+# ovs-dpctl show br0 | grep tap | awk '{print $3}' \
+#   | xargs -I '{}' ovs-vsctl del-port br0  '{}'
+# 
+# # clean up ip addresses from bridge interface
+# ip addr show  dev br0 | grep 10\\.\[23\]\\. | awk '{print $2;}' \
+#   |  xargs -I '{}'  ip addr del  '{}' dev br0
+# # clean up ip addresses from bridge interface
+# ip addr show  dev br0 | grep 172\\.31\\. | awk '{print $2;}' \
+#   |  xargs -I '{}'  ip addr del  '{}' dev br0
+# 
+# # cleaning default links for sp addresses
+# route -n | grep 172\\.31\\.  | awk '{print $1" netmask "$3" gw "$2;}' \
+#     | xargs -I '{}' echo route del -net '{}' > /tmp/sp_route_cleanup.sh
+# 
+# # cleanning up ssh routes
+# route -n | grep 10\\.\[23\]\\. | awk '{print $1" netmask "$3" gw "$2;}' \
+#     | xargs -I '{}' echo route del -net '{}' >> /tmp/sp_route_cleanup.sh
+# 
+# sudo sh /tmp/sp_route_cleanup.sh   
+# 
+# ovs-ofctl del-flows br0
+# ovs-ofctl add-flow br0 hard_timeout=0,idle_timeout=0,priority=1,in_port=1,action=LOCAL
+# ovs-ofctl add-flow br0 hard_timeout=0,idle_timeout=0,priority=1,in_port=LOCAL,action=output:1
 ./client.native $NODE_NAME $IP $SIG_PORT
diff --git a/scripts/run-server b/scripts/run-server
--- a/scripts/run-server
+++ b/scripts/run-server
@@ -1,11 +1,24 @@
 #!/usr/bin/env bash
-set -ex
+set -e
 
-d=$(dirname $(readlink -f $0))
+canonical_readlink ()
+{
+  cd `dirname $1`;
+  __filename=`basename $1`;
+  if [ -h "$__filename" ]; then
+    canonical_readlink `readlink $__filename`;
+  else
+    echo "`pwd`/$__filename";
+  fi
+}
+
+d=$(dirname $(canonical_readlink $0))
 if [ ! -e "${d}/PASSWD" ]; then
   echo Create file called PASSWD in ${d} containing your password
   exit 1
 fi
+
+
 
 IP_RANGE=`cat lib/config.ml | grep ip_slash_24 |  tail -1 | awk '{print $4}' | sed 's/"//g'`
 NUM=`cat lib/config.ml | grep signpost_number |  tail -1 | awk '{print $4}'`
@@ -21,30 +34,28 @@ if [ "`ps -e | grep iodined | wc -l `" -eq 0 ]; then
 fi
 
 # clean up ports from openvswitch switch
-ovs-vsctl show | grep Interface | grep tap | awk '{print $2;}' \
-    | xargs -I '{}' ovs-vsctl del-port br0  '{}'
-ovs-dpctl show br0 | grep tap | awk '{print $3}' \
-    | xargs -I '{}' ovs-vsctl del-port br0  '{}'
-
-# clean up ip addresses from bridge interface
-ip addr show  dev br0 | grep 10\\.\[23\]\\. | awk '{print $2;}' |\
-  xargs -I '{}'  ip addr del  '{}' dev br0
-ip addr show  dev br0 | grep 172\\.31\\. | awk '{print $2;}' |\
-  xargs -I '{}'  ip addr del  '{}' dev br0
-
-# cleaning default links for sp addresses
-route -n | grep 172\\.31\\.  | awk '{print $1" gw "$2;}' \
-  | xargs -I '{}' echo route del '{}' > /tmp/sp_route_cleanup.sh
-
-# cleanning up ssh routes
-route -n | grep 10\\.\[23\]\\. | awk '{print $1" netmask "$3" gw "$2;}' \
-    | xargs -I '{}' echo route del -net '{}' >> /tmp/sp_route_cleanup.sh
-sh /tmp/sp_route_cleanup.sh
-
-intf=`cat lib/config.ml | grep net_intf | awk -F '=' '{print $2}' | tr -d \ \"`
-port_id=`ovs-dpctl show br0 | grep eth0 | grep -o "port [1-9]*" | sed -e "s/port //g"`
-ovs-ofctl del-flows br0
-ovs-ofctl add-flow br0 hard_timeout=7200,in_port=$port_id,priority=1,action=local
-ovs-ofctl add-flow br0 hard_timeout=7200,in_port=LOCAL,priority=1,action=output:$port_id
+# ovs-vsctl show | grep Interface | grep tap | awk '{print $2;}' \
+#   | xargs -I '{}' ovs-vsctl del-port br0  '{}'
+# ovs-dpctl show br0 | grep tap | awk '{print $3}' \
+#   | xargs -I '{}' ovs-vsctl del-port br0  '{}'
+# 
+# # clean up ip addresses from bridge interface
+# ip addr show  dev br0 | grep 10\\.\[23\]\\. | awk '{print $2;}' |\
+#   xargs -I '{}'  ip addr del  '{}' dev br0
+# ip addr show  dev br0 | grep 172\\.31\\. | awk '{print $2;}' |\
+#   xargs -I '{}'  ip addr del  '{}' dev br0
+# 
+# # cleaning default links for sp addresses
+# route -n | grep 172\\.31\\.  | awk '{print $1" gw "$2;}' \
+#   | xargs -I '{}' echo route del '{}' > /tmp/sp_route_cleanup.sh
+# 
+# # cleanning up ssh routes
+# route -n | grep 10\\.\[23\]\\. | awk '{print $1" netmask "$3" gw "$2;}' \
+#   | xargs -I '{}' echo route del -net '{}' >> /tmp/sp_route_cleanup.sh
+# sh /tmp/sp_route_cleanup.sh
+# 
+# 
+# ovs-ofctl del-flows br0
+# ovs-ofctl add-flow br0 hard_timeout=7200,priority=1,action=NORMAL
 
 ../server.native
